import { graphqlClient } from "../../../shared/api/graphql-client";
import type { AcademicClass, ClassInput, Program, ProgramInput, Section, SectionInput, Subject, SubjectInput, TeachingAssignment, TeachingAssignmentInput } from "../model/academic-structure.types";
const programFields = "id campusId code name description status";
const classFields = "id campusId programId code name description status";
const sectionFields = "id campusId programId classId code name description status";
const subjectFields = "id campusId programId classId code name subjectType credits status";
const filterQuery = (campusId: string) => ({ filter: { campusId } });
export async function listPrograms(campusId: string) { return (await graphqlClient<{ academicPrograms: Program[] }, { filter: { campusId: string } }>(`query AcademicPrograms($filter: AcademicProgramFilter) { academicPrograms(filter: $filter) { ${programFields} } }`, filterQuery(campusId))).academicPrograms; }
export async function listClasses(campusId: string) { return (await graphqlClient<{ academicClasses: AcademicClass[] }, { filter: { campusId: string } }>(`query AcademicClasses($filter: AcademicClassFilter) { academicClasses(filter: $filter) { ${classFields} } }`, filterQuery(campusId))).academicClasses; }
export async function listSections(campusId: string) { return (await graphqlClient<{ academicSections: Section[] }, { filter: { campusId: string } }>(`query AcademicSections($filter: AcademicSectionFilter) { academicSections(filter: $filter) { ${sectionFields} } }`, filterQuery(campusId))).academicSections; }
export async function listSubjects(campusId: string) { return (await graphqlClient<{ academicSubjects: Subject[] }, { filter: { campusId: string } }>(`query AcademicSubjects($filter: AcademicSubjectFilter) { academicSubjects(filter: $filter) { ${subjectFields} } }`, filterQuery(campusId))).academicSubjects; }
export async function createProgram(input: ProgramInput) { return (await graphqlClient<{ createAcademicProgram: Program }, { input: ProgramInput }>(`mutation CreateAcademicProgram($input: CreateAcademicProgramInput!) { createAcademicProgram(input: $input) { ${programFields} } }`, { input })).createAcademicProgram; }
export async function createClass(input: ClassInput) { return (await graphqlClient<{ createAcademicClass: AcademicClass }, { input: ClassInput }>(`mutation CreateAcademicClass($input: CreateAcademicClassInput!) { createAcademicClass(input: $input) { ${classFields} } }`, { input })).createAcademicClass; }
export async function createSection(input: SectionInput) { return (await graphqlClient<{ createAcademicSection: Section }, { input: SectionInput }>(`mutation CreateAcademicSection($input: CreateAcademicSectionInput!) { createAcademicSection(input: $input) { ${sectionFields} } }`, { input })).createAcademicSection; }
export async function createSubject(input: SubjectInput) { return (await graphqlClient<{ createAcademicSubject: Subject }, { input: SubjectInput }>(`mutation CreateAcademicSubject($input: CreateAcademicSubjectInput!) { createAcademicSubject(input: $input) { ${subjectFields} } }`, { input })).createAcademicSubject; }
const assignmentFields = "id campusId academicYearId employeeId employeeName role programId classId sectionId subjectId status createdAt updatedAt deactivatedAt";
export async function listTeachingAssignments(filter: { campusId: string; academicYearId?: string }) { return (await graphqlClient<{ teachingAssignments: TeachingAssignment[] }, { filter: typeof filter }>(`query TeachingAssignments($filter:TeachingAssignmentFilter!){ teachingAssignments(filter:$filter){ ${assignmentFields} } }`, { filter })).teachingAssignments; }
export async function createTeachingAssignment(input: TeachingAssignmentInput) { return (await graphqlClient<{ createTeachingAssignment: TeachingAssignment }, { input: TeachingAssignmentInput }>(`mutation CreateTeachingAssignment($input:CreateTeachingAssignmentInput!){ createTeachingAssignment(input:$input){ ${assignmentFields} } }`, { input })).createTeachingAssignment; }
export async function deactivateTeachingAssignment(id: string) { return (await graphqlClient<{ deactivateTeachingAssignment: TeachingAssignment }, { id: string }>(`mutation DeactivateTeachingAssignment($id:ID!){ deactivateTeachingAssignment(id:$id){ ${assignmentFields} } }`, { id })).deactivateTeachingAssignment; }
