import { graphqlClient } from "../../../shared/api/graphql-client";
import type { AcademicResponsibility, AcademicRoom, ClassTimetableGenerationResult, ClassSetupWorkspace, CurriculumSubject, EmployeeCampusAssignment, FacultyWorkload, PeriodSet, PeriodSlot, Readiness, SectionSubjectException, SubjectBatch, SubjectBatchMembership, SubjectCatalogueItem, SubjectChoiceGroup, SubjectComponent, SubjectOffering, SubjectPlan, TeacherAssignment, TeacherEligibility, TeachingGroup, TeachingGroupMembership, TimetableConflict, TimetableConstraint, TimetableEntry, TimetableGenerationResult, TimetableVersion } from "../model/academic-planning.types";
const query = async <T>(field:string,selection:string,variables:Record<string,unknown>={},declaration="") => (await graphqlClient<Record<string,T>,Record<string,unknown>>(`query AcademicPlanning${declaration}{${field}{${selection}}}`,variables))[field.split("(")[0]!.trim()] as T;
const catalogueFields="id code name shortName description departmentId subjectDomain status version";
export const listSubjectCatalogue=(filter:Record<string,unknown>={})=>query<SubjectCatalogueItem[]>("subjectCatalogue(filter:$filter)",catalogueFields,{filter},"($filter:SubjectCatalogueFilter)");
export const createSubjectCatalogueItem=(input:{name:string;shortName?:string;description?:string;departmentId?:string;subjectDomain?:string})=>(graphqlClient<{createSubjectCatalogueItem:SubjectCatalogueItem},{input:typeof input}>(`mutation($input:CreateSubjectCatalogueItemInput!){createSubjectCatalogueItem(input:$input){${catalogueFields}}}`,{input})).then(r=>r.createSubjectCatalogueItem);
export const updateSubjectCatalogueItem=(id:string,input:Record<string,unknown>)=>(graphqlClient<{updateSubjectCatalogueItem:SubjectCatalogueItem},{id:string;input:Record<string,unknown>}>(`mutation($id:ID!,$input:UpdateSubjectCatalogueItemInput!){updateSubjectCatalogueItem(id:$id,input:$input){${catalogueFields}}}`,{id,input})).then(r=>r.updateSubjectCatalogueItem);
export const deactivateSubjectCatalogueItem=(id:string,reason:string)=>(graphqlClient<{deactivateSubjectCatalogueItem:SubjectCatalogueItem},{id:string;reason:string}>(`mutation($id:ID!,$reason:String!){deactivateSubjectCatalogueItem(id:$id,reason:$reason){${catalogueFields}}}`,{id,reason})).then(r=>r.deactivateSubjectCatalogueItem);
const curriculumFields="id academicUnitId curriculumId programId academicLevelId subjectCatalogueId subjectCategory credits isMandatory status version";
export const listCurriculumSubjects=()=>query<CurriculumSubject[]>("curriculumSubjects",curriculumFields);
export const createCurriculumSubject=(input:Record<string,unknown>)=>(graphqlClient<{createCurriculumSubject:CurriculumSubject},{input:Record<string,unknown>}>(`mutation($input:CreateCurriculumSubjectInput!){createCurriculumSubject(input:$input){${curriculumFields}}}`,{input})).then(r=>r.createCurriculumSubject);
const componentFields="id curriculumSubjectId componentType baselinePeriodsPerWeek workloadMultiplier preferredSessionLength requiresConsecutivePeriods status";
export const listSubjectComponents=(curriculumSubjectId?:string)=>query<SubjectComponent[]>(`subjectComponents(curriculumSubjectId:$curriculumSubjectId)`,componentFields,{curriculumSubjectId},"($curriculumSubjectId:ID)");
export const createSubjectComponent=(input:Record<string,unknown>)=>(graphqlClient<{createSubjectComponent:SubjectComponent},{input:Record<string,unknown>}>(`mutation($input:CreateSubjectComponentInput!){createSubjectComponent(input:$input){${componentFields}}}`,{input})).then(r=>r.createSubjectComponent);
const planFields="id campusId academicYearId academicUnitId curriculumId programId academicLevelId curriculumSubjectId appliesToAllSections componentPlans{subjectComponentId plannedPeriodsPerWeek preferredSessionLength isOverride overrideReason} status";
export const listSubjectPlans=(filter:Record<string,unknown>)=>query<SubjectPlan[]>("academicYearSubjectPlans(filter:$filter)",planFields,{filter},"($filter:SubjectPlanFilter)");
export const createSubjectPlan=(input:Record<string,unknown>)=>(graphqlClient<{createAcademicYearSubjectPlan:SubjectPlan},{input:Record<string,unknown>}>(`mutation($input:CreateAcademicYearSubjectPlanInput!){createAcademicYearSubjectPlan(input:$input){${planFields}}}`,{input})).then(r=>r.createAcademicYearSubjectPlan);
export const activateSubjectPlan=(id:string)=>(graphqlClient<{activateAcademicYearSubjectPlan:SubjectPlan},{id:string}>(`mutation($id:ID!){activateAcademicYearSubjectPlan(id:$id){${planFields}}}`,{id})).then(r=>r.activateAcademicYearSubjectPlan);
const exceptionFields="id academicYearId subjectPlanId sectionId action reason effectiveFrom effectiveUntil status";
export const listSectionSubjectExceptions=(filter:Record<string,unknown>)=>query<SectionSubjectException[]>("sectionSubjectExceptions(filter:$filter)",exceptionFields,{filter},"($filter:LearningDeliveryFilter)");
export const createSectionSubjectException=(input:Record<string,unknown>)=>graphqlClient<{createSectionSubjectException:SectionSubjectException},{input:Record<string,unknown>}>(`mutation($input:CreateSectionSubjectExceptionInput!){createSectionSubjectException(input:$input){${exceptionFields}}}`,{input}).then(r=>r.createSectionSubjectException);
const groupFields="id campusId academicYearId type name code homeSectionId sourceSectionIds capacity status";
export const listTeachingGroups=(filter:Record<string,unknown>)=>query<TeachingGroup[]>("teachingGroups(filter:$filter)",groupFields,{filter},"($filter:LearningDeliveryFilter)");
export const createTeachingGroup=(input:Record<string,unknown>)=>(graphqlClient<{createTeachingGroup:TeachingGroup},{input:Record<string,unknown>}>(`mutation($input:CreateTeachingGroupInput!){createTeachingGroup(input:$input){${groupFields}}}`,{input})).then(r=>r.createTeachingGroup);
const membershipFields="id teachingGroupId studentId enrollmentId membershipSource effectiveFrom effectiveUntil status reason";
export const listTeachingGroupMemberships=(filter:Record<string,unknown>)=>query<TeachingGroupMembership[]>("teachingGroupMemberships(filter:$filter)",membershipFields,{filter},"($filter:LearningDeliveryFilter)");
export const addTeachingGroupMembership=(input:Record<string,unknown>)=>graphqlClient<{addTeachingGroupMembership:TeachingGroupMembership},{input:Record<string,unknown>}>(`mutation($input:AddTeachingGroupMembershipInput!){addTeachingGroupMembership(input:$input){${membershipFields}}}`,{input}).then(r=>r.addTeachingGroupMembership);
const batchFields="id campusId academicYearId academicUnitId curriculumId programId academicLevelId curriculumSubjectId subjectComponentId name code batchType sourceSectionIds capacity maximumStrength effectiveFrom effectiveUntil status";
export const listSubjectBatches=(filter:Record<string,unknown>)=>query<SubjectBatch[]>("subjectBatches(filter:$filter)",batchFields,{filter},"($filter:LearningDeliveryFilter)");
export const createSubjectBatch=(input:Record<string,unknown>)=>graphqlClient<{createSubjectBatch:SubjectBatch},{input:Record<string,unknown>}>(`mutation($input:CreateSubjectBatchInput!){createSubjectBatch(input:$input){${batchFields}}}`,{input}).then(r=>r.createSubjectBatch);
const batchMembershipFields="id subjectBatchId studentId enrollmentId membershipSource effectiveFrom effectiveUntil status reason";
export const listSubjectBatchMemberships=(filter:Record<string,unknown>)=>query<SubjectBatchMembership[]>("subjectBatchMemberships(filter:$filter)",batchMembershipFields,{filter},"($filter:LearningDeliveryFilter)");
export const addSubjectBatchMembership=(input:Record<string,unknown>)=>graphqlClient<{addSubjectBatchMembership:SubjectBatchMembership},{input:Record<string,unknown>}>(`mutation($input:AddSubjectBatchMembershipInput!){addSubjectBatchMembership(input:$input){${batchMembershipFields}}}`,{input}).then(r=>r.addSubjectBatchMembership);
const choiceGroupFields="id campusId academicYearId academicUnitId programId academicLevelId name code minimumSelections maximumSelections optionCurriculumSubjectIds status";
export const listSubjectChoiceGroups=(filter:Record<string,unknown>)=>query<SubjectChoiceGroup[]>("subjectChoiceGroups(filter:$filter)",choiceGroupFields,{filter},"($filter:LearningDeliveryFilter)");
export const createSubjectChoiceGroup=(input:Record<string,unknown>)=>graphqlClient<{createSubjectChoiceGroup:SubjectChoiceGroup},{input:Record<string,unknown>}>(`mutation($input:CreateSubjectChoiceGroupInput!){createSubjectChoiceGroup(input:$input){${choiceGroupFields}}}`,{input}).then(r=>r.createSubjectChoiceGroup);
const offeringFields="id campusId academicYearId subjectPlanId curriculumSubjectId subjectComponentId subjectName targetType sectionId subjectBatchId teachingGroupId requiredPeriodsPerWeek requiredConsecutiveSlots preferredSessionLength readinessStatus status";
export const listSubjectOfferings=(filter:Record<string,unknown>)=>query<SubjectOffering[]>("subjectOfferings(filter:$filter)",offeringFields,{filter},"($filter:LearningDeliveryFilter)");
export const createSubjectOffering=(input:Record<string,unknown>)=>(graphqlClient<{createSubjectOffering:SubjectOffering},{input:Record<string,unknown>}>(`mutation($input:CreateSubjectOfferingInput!){createSubjectOffering(input:$input){${offeringFields}}}`,{input})).then(r=>r.createSubjectOffering);
const assignmentFields="id subjectOfferingId employeeId assignmentRole workloadSharePercentage eligibilityStatus status";
export const listOfferingAssignments=(filter:Record<string,unknown>)=>query<TeacherAssignment[]>("offeringTeacherAssignments(filter:$filter)",assignmentFields,{filter},"($filter:FacultyPlanningFilter)");
export const assignOfferingTeacher=(input:Record<string,unknown>)=>(graphqlClient<{assignOfferingTeacher:TeacherAssignment},{input:Record<string,unknown>}>(`mutation($input:AssignOfferingTeacherInput!){assignOfferingTeacher(input:$input){${assignmentFields}}}`,{input})).then(r=>r.assignOfferingTeacher);
export const assignEmployeeCampus=(input:Record<string,unknown>)=>graphqlClient<{assignEmployeeCampus:{id:string}},{input:Record<string,unknown>}>(`mutation($input:AssignEmployeeCampusInput!){assignEmployeeCampus(input:$input){id}}`,{input}).then(r=>r.assignEmployeeCampus);
export const addTeacherEligibility=(input:Record<string,unknown>)=>graphqlClient<{addTeacherEligibility:{id:string}},{input:Record<string,unknown>}>(`mutation($input:AddTeacherEligibilityInput!){addTeacherEligibility(input:$input){id}}`,{input}).then(r=>r.addTeacherEligibility);
export const listEmployeeCampusAssignments=(filter:Record<string,unknown>)=>query<EmployeeCampusAssignment[]>("employeeCampusAssignments(filter:$filter)","id employeeId campusId assignmentType availableForTeaching effectiveFrom effectiveUntil status",{filter},"($filter:FacultyPlanningFilter)");
export const listTeacherEligibility=(filter:Record<string,unknown>)=>query<TeacherEligibility[]>("teacherSubjectEligibility(filter:$filter)","id employeeId subjectCatalogueId qualificationReference proficiencyLevel effectiveFrom effectiveUntil status",{filter},"($filter:FacultyPlanningFilter)");
export const listAcademicResponsibilities=(filter:Record<string,unknown>)=>query<AcademicResponsibility[]>("academicResponsibilities(filter:$filter)","id employeeId campusId academicYearId responsibilityType academicLevelId sectionId status",{filter},"($filter:FacultyPlanningFilter)");
export const addAcademicResponsibility=(input:Record<string,unknown>)=>graphqlClient<{addAcademicResponsibility:AcademicResponsibility},{input:Record<string,unknown>}>(`mutation($input:AddAcademicResponsibilityInput!){addAcademicResponsibility(input:$input){id employeeId campusId academicYearId responsibilityType academicLevelId sectionId status}}`,{input}).then(r=>r.addAcademicResponsibility);
export const getFacultyWorkload=(employeeId:string)=>query<FacultyWorkload>("facultyWorkload(employeeId:$employeeId)","employeeId contactPeriods weightedUnits exceedsContactLimit exceedsWeightedLimit campusBreakdown{campusId contactPeriods weightedUnits}",{employeeId},"($employeeId:ID!)");
export const listTeacherWorkloadPolicies=(filter:Record<string,unknown>={})=>query<Array<{id:string;academicUnitId?:string;maximumContactPeriodsPerWeek?:number;maximumWeightedUnitsPerWeek?:number;maximumPeriodsPerDay?:number;componentMultipliers:Array<{componentType:string;multiplier:number}>;status:string}>>("teacherWorkloadPolicies(filter:$filter)","id academicUnitId maximumContactPeriodsPerWeek maximumWeightedUnitsPerWeek maximumPeriodsPerDay componentMultipliers{componentType multiplier} status",{filter},"($filter:FacultyPlanningFilter)");
export const saveTeacherWorkloadPolicy=(input:Record<string,unknown>)=>graphqlClient<{saveTeacherWorkloadPolicy:{id:string}},{input:Record<string,unknown>}>(`mutation($input:SaveTeacherWorkloadPolicyInput!){saveTeacherWorkloadPolicy(input:$input){id}}`,{input}).then(r=>r.saveTeacherWorkloadPolicy);
export const getTimetableReadiness=(campusId:string,academicYearId:string)=>query<Readiness>("timetableReadiness(campusId:$campusId academicYearId:$academicYearId)","campusId academicYearId totalOfferings readyOfferings ready issues{subjectOfferingId message}",{campusId,academicYearId},"($campusId:ID!$academicYearId:ID!)");
export const listPeriodSets=(filter:Record<string,unknown>)=>query<PeriodSet[]>("timetablePeriodSets(filter:$filter)","id campusId academicYearId name description instructionType preferences applicableDays status",{filter},"($filter:TimetableFilter)");
export const listPeriodSlots=(filter:Record<string,unknown>)=>query<PeriodSlot[]>("timetablePeriodSlots(filter:$filter)","id periodSetId sequence label startTime endTime slotType",{filter},"($filter:TimetableFilter)");
export const listTimetableVersions=(filter:Record<string,unknown>)=>query<TimetableVersion[]>("timetableVersions(filter:$filter)","id campusId academicYearId academicUnitId name versionNumber status scopeType programId academicLevelId sectionId periodSetId",{filter},"($filter:TimetableFilter)");
export const listTimetableEntries=(filter:Record<string,unknown>)=>query<TimetableEntry[]>("timetableEntries(filter:$filter)","id timetableVersionId dayOfWeek periodSlotIds subjectOfferingId sectionId subjectBatchId teachingGroupId teachingAssignmentIds roomId",{filter},"($filter:TimetableFilter)");
export const listAcademicRooms=(filter:Record<string,unknown>)=>query<AcademicRoom[]>("academicRooms(filter:$filter)","id campusId code name roomType capacity status",{filter},"($filter:TimetableFilter)");
export const listTimetableConflicts=(filter:Record<string,unknown>)=>query<TimetableConflict[]>("timetableConflicts(filter:$filter)","id conflictType severity message resolutionStatus",{filter},"($filter:TimetableFilter)");
export const listTimetableConstraints=(filter:Record<string,unknown>)=>query<TimetableConstraint[]>("timetableConstraints(filter:$filter)","id academicYearId timetableVersionId scopeType scopeId constraintType severity parameters status version",{filter},"($filter:TimetableFilter)");
export function serializePeriodSetInput(input:Record<string,unknown>) {
  return {
    ...input,
    ...(input.preferences === undefined
      ? {}
      : {preferences:typeof input.preferences === "string" ? input.preferences : JSON.stringify(input.preferences)}),
  };
}
export const createPeriodSet=(input:Record<string,unknown>)=>{
  const serializedInput=serializePeriodSetInput(input);
  return graphqlClient<{createTimetablePeriodSet:PeriodSet},{input:Record<string,unknown>}>(`mutation($input:CreateTimetablePeriodSetInput!){createTimetablePeriodSet(input:$input){id campusId academicYearId name description instructionType preferences applicableDays status}}`,{input:serializedInput}).then(r=>r.createTimetablePeriodSet);
};
export const createPeriodSlot=(input:Record<string,unknown>)=>graphqlClient<{createTimetablePeriodSlot:PeriodSlot},{input:Record<string,unknown>}>(`mutation($input:CreateTimetablePeriodSlotInput!){createTimetablePeriodSlot(input:$input){id periodSetId sequence label startTime endTime slotType}}`,{input}).then(r=>r.createTimetablePeriodSlot);
export const createAcademicRoom=(input:Record<string,unknown>)=>graphqlClient<{createAcademicRoom:AcademicRoom},{input:Record<string,unknown>}>(`mutation($input:CreateAcademicRoomInput!){createAcademicRoom(input:$input){id campusId code name roomType capacity status}}`,{input}).then(r=>r.createAcademicRoom);
export function serializeTimetableConstraintInput(input:Record<string,unknown>) {
  return {
    ...input,
    parameters: typeof input.parameters === "string"
      ? input.parameters
      : JSON.stringify(input.parameters ?? {}),
  };
}
export const createTimetableConstraint=(input:Record<string,unknown>)=>{
  const serializedInput=serializeTimetableConstraintInput(input);
  return graphqlClient<{createTimetableConstraint:{id:string}},{input:Record<string,unknown>}>(`mutation($input:CreateTimetableConstraintInput!){createTimetableConstraint(input:$input){id}}`,{input:serializedInput}).then(r=>r.createTimetableConstraint);
};
export const createTimetableVersion=(input:Record<string,unknown>)=>graphqlClient<{createTimetableVersion:TimetableVersion},{input:Record<string,unknown>}>(`mutation($input:CreateTimetableVersionInput!){createTimetableVersion(input:$input){id campusId academicYearId academicUnitId name versionNumber status scopeType programId academicLevelId sectionId periodSetId}}`,{input}).then(r=>r.createTimetableVersion);
export const addTimetableEntry=(input:Record<string,unknown>)=>graphqlClient<{addTimetableEntry:TimetableEntry},{input:Record<string,unknown>}>(`mutation($input:AddTimetableEntryInput!){addTimetableEntry(input:$input){id timetableVersionId dayOfWeek periodSlotIds subjectOfferingId sectionId subjectBatchId teachingGroupId teachingAssignmentIds roomId}}`,{input}).then(r=>r.addTimetableEntry);
export const updateTimetableEntry=(id:string,input:Record<string,unknown>)=>graphqlClient<{updateTimetableEntry:TimetableEntry},{id:string;input:Record<string,unknown>}>(`mutation($id:ID!,$input:AddTimetableEntryInput!){updateTimetableEntry(id:$id,input:$input){id timetableVersionId dayOfWeek periodSlotIds subjectOfferingId sectionId subjectBatchId teachingGroupId teachingAssignmentIds roomId}}`,{id,input}).then(r=>r.updateTimetableEntry);
export const deactivateTimetableEntry=(id:string)=>graphqlClient<{deactivateTimetableEntry:TimetableEntry},{id:string}>(`mutation($id:ID!){deactivateTimetableEntry(id:$id){id status}}`,{id}).then(r=>r.deactivateTimetableEntry);
export const createTimetableRevision=(id:string)=>graphqlClient<{createTimetableRevision:TimetableVersion},{id:string}>(`mutation($id:ID!){createTimetableRevision(id:$id){id campusId academicYearId academicUnitId name versionNumber status scopeType programId academicLevelId sectionId periodSetId}}`,{id}).then(r=>r.createTimetableRevision);
export const generateTimetable=(id:string)=>graphqlClient<{generateTimetable:TimetableGenerationResult},{id:string}>(`mutation($id:ID!){generateTimetable(id:$id){success requiredLessons placedLessons unscheduledLessons{subjectOfferingId remainingPeriods reason}}}`,{id}).then(r=>r.generateTimetable);
export const validateTimetable=(id:string)=>graphqlClient<{validateTimetable:{run:{id:string;status:string;hardConflictCount:number;warningCount:number};conflicts:Array<{message:string;severity:string}>}},{id:string}>(`mutation($id:ID!){validateTimetable(id:$id){run{id status hardConflictCount warningCount} conflicts{message severity}}}`,{id}).then(r=>r.validateTimetable);
export const publishTimetable=(id:string,validationRunId:string)=>graphqlClient<{publishTimetable:TimetableVersion},{id:string;validationRunId:string}>(`mutation($id:ID!,$validationRunId:ID!){publishTimetable(id:$id,validationRunId:$validationRunId){id campusId academicYearId name versionNumber status periodSetId}}`,{id,validationRunId}).then(r=>r.publishTimetable);
const scheduleFields=`academicClass{id name programId status} sections{id name classId status} subjects{subjectPlanId curriculumSubjectId subjectName subjectCategory isMandatory periodsPerWeek offeringCount sectionCount primaryTeacherIds status} periodSets{id campusId academicYearId name description instructionType preferences applicableDays status} versions{id campusId academicYearId academicUnitId name versionNumber status scopeType programId academicLevelId sectionId periodSetId} currentVersion{id campusId academicYearId academicUnitId name versionNumber status scopeType programId academicLevelId sectionId periodSetId} entries{id timetableVersionId dayOfWeek periodSlotIds subjectOfferingId sectionId subjectBatchId teachingGroupId teachingAssignmentIds roomId} slots{id periodSetId sequence label startTime endTime slotType} offerings{${offeringFields}} assignments{id subjectOfferingId employeeId assignmentRole status}`;
export const getClassSetupWorkspace=(input:{campusId:string;academicYearId:string;classId:string})=>graphqlClient<{classSetupWorkspace:ClassSetupWorkspace},{input:typeof input}>(`query($input:ClassSetupContextInput!){classSetupWorkspace(input:$input){${scheduleFields}}}`,{input}).then(r=>r.classSetupWorkspace);
export const generateClassTimetable=(input:{campusId:string;academicYearId:string;classId:string})=>graphqlClient<{generateClassTimetable:ClassTimetableGenerationResult},{input:typeof input}>(`mutation($input:ClassSetupContextInput!){generateClassTimetable(input:$input){${scheduleFields} generation{success requiredLessons placedLessons remainingLessons issues} validation{run{id status hardConflictCount warningCount} conflicts{message severity}}}}`,{input}).then(r=>r.generateClassTimetable);
export const updateClassSetupSubject=(input:{campusId:string;academicYearId:string;classId:string;subjectPlanId:string;componentPlans:Array<{subjectComponentId:string;plannedPeriodsPerWeek:number}>})=>graphqlClient<{updateClassSetupSubject:ClassSetupWorkspace},{input:typeof input}>(`mutation($input:UpdateClassSetupSubjectInput!){updateClassSetupSubject(input:$input){${scheduleFields}}}`,{input}).then(r=>r.updateClassSetupSubject);
export const removeClassSetupSubject=(input:{campusId:string;academicYearId:string;classId:string;subjectPlanId:string;reason:string})=>graphqlClient<{removeClassSetupSubject:ClassSetupWorkspace},{input:typeof input}>(`mutation($input:RemoveClassSetupSubjectInput!){removeClassSetupSubject(input:$input){${scheduleFields}}}`,{input}).then(r=>r.removeClassSetupSubject);
export const saveClassSetupTiming=(input:{campusId:string;academicYearId:string;classId:string;name:string;applicableDays:string[];effectiveFrom:string;effectiveUntil?:string;slots:Array<{label:string;startTime:string;endTime:string;slotType:string}>})=>graphqlClient<{saveClassSetupTiming:ClassSetupWorkspace},{input:typeof input}>(`mutation($input:SaveClassSetupTimingInput!){saveClassSetupTiming(input:$input){${scheduleFields}}}`,{input}).then(r=>r.saveClassSetupTiming);
