import { useCallback, useEffect, useState } from "react";
import { Download, FileBadge, Plus, X } from "lucide-react";
import { listStudents } from "../../students/api/students.api";
import type { Student } from "../../students/model/student.types";
import { useSelectedCampus } from "../../tenant-settings/model/selected-campus-provider";
import { useSelectedAcademicYear } from "../../tenant-settings/model/selected-academic-year-provider";
import { downloadStudentDocument, issueStudentDocument, listStudentDocuments, revokeStudentDocument } from "../api/student-documents.api";
import type { StudentDocument, StudentDocumentType } from "../model/student-document.types";
import { Badge } from "../../../shared/ui/badge";import { Button } from "../../../shared/ui/button";import { Input } from "../../../shared/ui/input";import { Label } from "../../../shared/ui/label";import { Modal } from "../../../shared/ui/modal";import { EmptyState, ErrorState, LoadingState } from "../../../shared/ui/page-state";import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "../../../shared/ui/table";
const types:Array<[StudentDocumentType,string]>=[["BONAFIDE_CERTIFICATE","Bonafide certificate"],["STUDY_CERTIFICATE","Study certificate"],["TRANSFER_CERTIFICATE","Transfer certificate"],["STUDENT_ID_CARD","Student ID card"]];
export function StudentDocumentsManagement(){const{selectedCampus}=useSelectedCampus(),{selectedAcademicYear}=useSelectedAcademicYear();const[rows,setRows]=useState<StudentDocument[]>([]),[students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[open,setOpen]=useState(false),[studentId,setStudentId]=useState(""),[documentType,setDocumentType]=useState<StudentDocumentType>("BONAFIDE_CERTIFICATE"),[purpose,setPurpose]=useState(""),[validUntil,setValidUntil]=useState("");
const load=useCallback(async()=>{if(!selectedCampus||!selectedAcademicYear)return setLoading(false);setLoading(true);try{const[data,studentRows]=await Promise.all([listStudentDocuments({campusId:selectedCampus.id,academicYearId:selectedAcademicYear.id}),listStudents({campusId:selectedCampus.id,academicYearId:selectedAcademicYear.id,status:"ACTIVE",limit:100})]);setRows(data);setStudents(studentRows)}catch(value){setError(value instanceof Error?value.message:"Unable to load certificates and ID cards")}finally{setLoading(false)}},[selectedAcademicYear,selectedCampus]);useEffect(()=>{void load()},[load]);
const issue=async()=>{try{setError(null);await issueStudentDocument({studentId,documentType,...(purpose.trim()?{purpose:purpose.trim()}:{}),...(validUntil?{validUntil:new Date(`${validUntil}T00:00:00.000Z`).toISOString()}: {})});setOpen(false);setStudentId("");setPurpose("");setValidUntil("");await load()}catch(value){setError(value instanceof Error?value.message:"Unable to issue document")}};
if(loading)return<LoadingState label="Loading certificates and ID cards"/>;return<section className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">Certificates and ID cards</h2><p className="text-sm text-slate-500">Issue numbered, tenant-branded student documents from authoritative enrollment data.</p></div><Button onClick={()=>setOpen(true)}><Plus size={15}/>Issue document</Button></header>{error&&<ErrorState message={error} retry={load}/>}
{rows.length?<div className="overflow-hidden rounded-lg border border-slate-200 bg-white"><Table><TableHeader><TableRow><TableHead>Document</TableHead><TableHead>Student</TableHead><TableHead>Type</TableHead><TableHead>Issued</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id}><TableCell className="font-mono text-xs">{row.documentNumber}</TableCell><TableCell><p className="font-semibold">{row.studentName}</p><p className="text-xs text-slate-400">{row.admissionNumber}</p></TableCell><TableCell>{types.find(([type])=>type===row.documentType)?.[1]}</TableCell><TableCell>{new Date(row.issuedAt).toLocaleDateString("en-IN")}</TableCell><TableCell><Badge variant={row.status==="ISSUED"?"success":"secondary"}>{row.status}</Badge></TableCell><TableCell><div className="flex gap-1"><Button variant="ghost" size="icon-sm" title="Download PDF" disabled={row.status!=="ISSUED"} onClick={()=>void downloadStudentDocument(row).catch(value=>setError(value instanceof Error?value.message:"Download failed"))}><Download size={15}/></Button>{row.status==="ISSUED"&&<Button variant="ghost" size="icon-sm" title="Revoke document" onClick={()=>{const reason=window.prompt("Reason for revocation");if(reason?.trim())void revokeStudentDocument(row.id,reason.trim()).then(load).catch(value=>setError(value instanceof Error?value.message:"Unable to revoke"))}}><X size={15}/></Button>}</div></TableCell></TableRow>)}</TableBody></Table></div>:<EmptyState title="No issued documents" description="Issue a certificate or ID card for an enrolled student."/>}
<Modal open={open} title="Issue student document" description={`${selectedCampus?.name??"No campus"} · ${selectedAcademicYear?.name??"No academic year"}`} onClose={()=>setOpen(false)}><div className="space-y-4"><div className="space-y-1.5"><Label>Student</Label><select value={studentId} onChange={e=>setStudentId(e.target.value)} className="h-9 w-full rounded-md border border-slate-200 px-2"><option value="">Select student</option>{students.map(student=><option key={student.id} value={student.id}>{student.name} · {student.admissionNumber}</option>)}</select></div><div className="space-y-1.5"><Label>Document type</Label><select value={documentType} onChange={e=>setDocumentType(e.target.value as StudentDocumentType)} className="h-9 w-full rounded-md border border-slate-200 px-2">{types.map(([type,name])=><option key={type} value={type}>{name}</option>)}</select></div><div className="space-y-1.5"><Label>Purpose</Label><Input value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Optional purpose or reference"/></div>{documentType==="STUDENT_ID_CARD"&&<div className="space-y-1.5"><Label>Valid until</Label><Input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></div>}<div className="flex justify-end"><Button disabled={!studentId} onClick={()=>void issue()}><FileBadge size={15}/>Issue document</Button></div></div></Modal></section>}
